AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
